#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         4
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus button1
bspc config focused_border_color "#29ADFF"

bspc config presel_feedback true
bspc config presel_feedback_color "#29ADFF"

bspc config normal_border_color "#1D2B5E"

bspc config top_monocle_padding 0
